# Generated by Django 4.1.2 on 2022-10-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_title",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
