# Generated by Django 4.1.2 on 2022-10-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_meta_description_article_meta_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
