# Generated by Django 4.1.2 on 2022-10-28 18:28

import articles.utils
import cfehome.storage.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cfehome.storage.utils.get_public_storage,
                upload_to=articles.utils.get_article_image_upload_to,
            ),
        ),
    ]
