# Generated by Django 4.1.2 on 2022-10-31 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "container",
                    models.TextField(
                        blank=True, help_text="Include any tag", null=True
                    ),
                ),
                (
                    "container_port",
                    models.CharField(
                        blank=True, default="8000", max_length=120, null=True
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "Select database"),
                            ("psql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("mongo", "MongoDB"),
                            ("na", "None"),
                        ],
                        default="na",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "allow_internet_traffic",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (None, "Select to allow internet traffic:"),
                            (1, "Enable"),
                            (0, "Disable"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "custom_domain_names",
                    models.TextField(
                        blank=True, help_text="Separate domains by comma", null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
