# Generated by Django 4.1.2 on 2022-11-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="namespace",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="app",
            name="database",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Select database"),
                    ("na", "No database"),
                    ("psql", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("mongo", "MongoDB"),
                ],
                default="na",
                max_length=120,
                null=True,
            ),
        ),
    ]
