# Generated by Django 4.1.2 on 2022-11-01 19:10

import apps.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_app_namespace_alter_app_database"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="replicas",
            field=models.IntegerField(
                default=1, validators=[apps.validators.validate_replica_count]
            ),
        ),
    ]
