# Generated by Django 4.1.2 on 2022-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_app_replicas"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="image_pull_policy",
            field=models.CharField(
                choices=[
                    ("Always", "Always"),
                    ("IfNotPresent", "If not already present"),
                ],
                default="Always",
                max_length=120,
            ),
        ),
    ]
