# Generated by Django 4.1.2 on 2022-11-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_app_image_pull_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="image_pull_policy",
            field=models.CharField(
                choices=[
                    ("Always", "Always"),
                    ("IfNotPresent", "If not already present"),
                ],
                default="Always",
                help_text="When should Kubernetes pull this image",
                max_length=120,
            ),
        ),
    ]
