# Generated by Django 4.1.2 on 2022-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_app_timestamp_app_updated_appvariable"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppEnvVariable",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps.appvariable",),
        ),
        migrations.CreateModel(
            name="AppSecretVariable",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps.appvariable",),
        ),
        migrations.AlterField(
            model_name="appvariable",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="appvariable",
            name="value_encoded",
            field=models.TextField(blank=True, null=True),
        ),
    ]
