# Generated by Django 4.1.2 on 2022-11-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_app_tls_secret_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
