# Generated by Django 4.1.2 on 2022-11-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_app_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="label",
            new_name="name",
        ),
    ]
