# Generated by Django 4.1.2 on 2022-11-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0011_alter_app_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
