# Generated by Django 4.1.2 on 2022-11-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_last_activated"),
        ("apps", "0012_alter_app_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="app",
            unique_together={("project", "name")},
        ),
    ]
