# Generated by Django 4.1.2 on 2022-11-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0013_alter_app_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="slug",
            new_name="app_id",
        ),
    ]
