# Generated by Django 4.1.2 on 2022-11-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0014_rename_slug_app_app_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="certificate_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="app",
            name="issue_certificate",
            field=models.BooleanField(default=False),
        ),
    ]
