# Generated by Django 4.1.2 on 2022-11-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0015_app_certificate_email_app_issue_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="issue_certificate",
        ),
        migrations.AddField(
            model_name="app",
            name="certifcate_issuer",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "Select to enable cert-manager issuer:"),
                    (1, "Enable"),
                    (0, "Disable"),
                ],
                default=1,
                null=True,
            ),
        ),
    ]
