# Generated by Django 4.1.2 on 2022-11-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0016_remove_app_issue_certificate_app_certifcate_issuer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="certifcate_issuer",
            new_name="certificate_issuer",
        ),
    ]
