# Generated by Django 4.1.2 on 2022-11-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_activated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
