# Generated by Django 4.1.2 on 2022-11-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_last_activated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="label",
            new_name="name",
        ),
    ]
