#!/bin/bash

INIT_POSTGRES_DB=${INIT_POSTGRES_DB:-"auto_django_db"} # roadtok8s_db
INIT_POSTGRES_USER=${INIT_POSTGRES_USER:-"auto_django_user"}
INIT_POSTGRES_PASSWORD=${INIT_POSTGRES_PASSWORD:-"auto_django_user_password"} 

cat << EOF >> db-init.sql
CREATE DATABASE $INIT_POSTGRES_DB;
CREATE USER $INIT_POSTGRES_USER WITH PASSWORD '$INIT_POSTGRES_PASSWORD'
ALTER ROLE $INIT_POSTGRES_USER SET client_encoding TO 'utf8';
ALTER ROLE $INIT_POSTGRES_USER SET default_transaction_isolation TO 'read committed';
ALTER ROLE $INIT_POSTGRES_USER SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE $INIT_POSTGRES_DB TO $INIT_POSTGRES_USER;
EOF