# Generated by Django 4.1.2 on 2022-10-17 18:51

import profiles.utils
from cfehome.storage.utils import get_public_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_timestamp_profile_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=get_public_storage,
                upload_to=profiles.utils.get_profile_image_upload_to,
            ),
        ),
    ]
