name: Test - Init Database for Django

# Controls when the workflow will run
on:
  # Allows you to call this workflow within another workflow
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggered based on the git event type
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  db_init_postgres_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./src
    # Add in environment variables for the entire "build" job
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost # default host value for the database
      POSTGRES_DB: default_db
      POSTGRES_PORT: 5432
      GITHUB_ACTIONS: true
      DJANGO_SECRET_KEY: test-key-not-good
      DATABASE_BACKEND: postgres
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install psql
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client
      - name: run db-init
        env:
          INIT_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          INIT_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          INIT_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          chmod +x src/config/db-init.sh
          # create db-init.sql
          bash src/config/db-init.sh
          cat db-init.sql
      - name: run postgres file
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGPORT: 5432
        run: |
          psql db-init.sql
     